# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\naios.agent\x1a\x0c\x63ommon.proto\"4\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\xd7\x01\n\x13\x41gentStatusResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x17\n\x0f\x63urrent_task_id\x18\x04 \x01(\t\x12\x17\n\x0ftasks_completed\x18\x05 \x01(\x05\x12\x14\n\x0ctasks_failed\x18\x06 \x01(\x05\x12\x16\n\x0euptime_seconds\x18\x07 \x01(\x03\x12\x11\n\tcpu_usage\x18\x08 \x01(\x01\x12\x17\n\x0fmemory_usage_mb\x18\t \x01(\x01\x32\xfb\x01\n\x05\x41gent\x12\x39\n\x0b\x45xecuteTask\x12\x11.aios.common.Task\x1a\x17.aios.common.TaskResult\x12@\n\nCancelTask\x12\x1d.aios.agent.CancelTaskRequest\x1a\x13.aios.common.Status\x12@\n\tGetStatus\x12\x12.aios.common.Empty\x1a\x1f.aios.agent.AgentStatusResponse\x12\x33\n\x08Shutdown\x12\x12.aios.common.Empty\x1a\x13.aios.common.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANCELTASKREQUEST']._serialized_start=41
  _globals['_CANCELTASKREQUEST']._serialized_end=93
  _globals['_AGENTSTATUSRESPONSE']._serialized_start=96
  _globals['_AGENTSTATUSRESPONSE']._serialized_end=311
  _globals['_AGENT']._serialized_start=314
  _globals['_AGENT']._serialized_end=565
# @@protoc_insertion_point(module_scope)
