# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_gateway_pb2 as api__gateway__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/aios.api_gateway.ApiGateway/Infer',
                request_serializer=api__gateway__pb2.ApiInferRequest.SerializeToString,
                response_deserializer=common__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.StreamInfer = channel.unary_stream(
                '/aios.api_gateway.ApiGateway/StreamInfer',
                request_serializer=api__gateway__pb2.ApiInferRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.GetBudget = channel.unary_unary(
                '/aios.api_gateway.ApiGateway/GetBudget',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.BudgetStatus.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/aios.api_gateway.ApiGateway/GetUsage',
                request_serializer=api__gateway__pb2.UsageRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.UsageResponse.FromString,
                _registered_method=True)


class ApiGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=api__gateway__pb2.ApiInferRequest.FromString,
                    response_serializer=common__pb2.InferenceResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=api__gateway__pb2.ApiInferRequest.FromString,
                    response_serializer=api__gateway__pb2.StreamChunk.SerializeToString,
            ),
            'GetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBudget,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.BudgetStatus.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=api__gateway__pb2.UsageRequest.FromString,
                    response_serializer=api__gateway__pb2.UsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.api_gateway.ApiGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.api_gateway.ApiGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.api_gateway.ApiGateway/Infer',
            api__gateway__pb2.ApiInferRequest.SerializeToString,
            common__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aios.api_gateway.ApiGateway/StreamInfer',
            api__gateway__pb2.ApiInferRequest.SerializeToString,
            api__gateway__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.api_gateway.ApiGateway/GetBudget',
            common__pb2.Empty.SerializeToString,
            api__gateway__pb2.BudgetStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.api_gateway.ApiGateway/GetUsage',
            api__gateway__pb2.UsageRequest.SerializeToString,
            api__gateway__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
