# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushEvent = channel.unary_unary(
                '/aios.memory.MemoryService/PushEvent',
                request_serializer=memory__pb2.Event.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRecentEvents = channel.unary_unary(
                '/aios.memory.MemoryService/GetRecentEvents',
                request_serializer=memory__pb2.RecentEventsRequest.SerializeToString,
                response_deserializer=memory__pb2.EventList.FromString,
                _registered_method=True)
        self.UpdateMetric = channel.unary_unary(
                '/aios.memory.MemoryService/UpdateMetric',
                request_serializer=memory__pb2.MetricUpdate.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMetric = channel.unary_unary(
                '/aios.memory.MemoryService/GetMetric',
                request_serializer=memory__pb2.MetricRequest.SerializeToString,
                response_deserializer=memory__pb2.MetricValue.FromString,
                _registered_method=True)
        self.GetSystemSnapshot = channel.unary_unary(
                '/aios.memory.MemoryService/GetSystemSnapshot',
                request_serializer=memory__pb2.Empty.SerializeToString,
                response_deserializer=memory__pb2.SystemSnapshot.FromString,
                _registered_method=True)
        self.StoreGoal = channel.unary_unary(
                '/aios.memory.MemoryService/StoreGoal',
                request_serializer=memory__pb2.GoalRecord.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateGoal = channel.unary_unary(
                '/aios.memory.MemoryService/UpdateGoal',
                request_serializer=memory__pb2.GoalUpdate.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActiveGoals = channel.unary_unary(
                '/aios.memory.MemoryService/GetActiveGoals',
                request_serializer=memory__pb2.Empty.SerializeToString,
                response_deserializer=memory__pb2.GoalList.FromString,
                _registered_method=True)
        self.StoreTask = channel.unary_unary(
                '/aios.memory.MemoryService/StoreTask',
                request_serializer=memory__pb2.TaskRecord.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTasksForGoal = channel.unary_unary(
                '/aios.memory.MemoryService/GetTasksForGoal',
                request_serializer=memory__pb2.GoalIdRequest.SerializeToString,
                response_deserializer=memory__pb2.TaskList.FromString,
                _registered_method=True)
        self.StoreToolCall = channel.unary_unary(
                '/aios.memory.MemoryService/StoreToolCall',
                request_serializer=memory__pb2.ToolCallRecord.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.StoreDecision = channel.unary_unary(
                '/aios.memory.MemoryService/StoreDecision',
                request_serializer=memory__pb2.Decision.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.StorePattern = channel.unary_unary(
                '/aios.memory.MemoryService/StorePattern',
                request_serializer=memory__pb2.Pattern.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.FindPattern = channel.unary_unary(
                '/aios.memory.MemoryService/FindPattern',
                request_serializer=memory__pb2.PatternQuery.SerializeToString,
                response_deserializer=memory__pb2.PatternResult.FromString,
                _registered_method=True)
        self.UpdatePatternStats = channel.unary_unary(
                '/aios.memory.MemoryService/UpdatePatternStats',
                request_serializer=memory__pb2.PatternStatsUpdate.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.StoreAgentState = channel.unary_unary(
                '/aios.memory.MemoryService/StoreAgentState',
                request_serializer=memory__pb2.AgentState.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAgentState = channel.unary_unary(
                '/aios.memory.MemoryService/GetAgentState',
                request_serializer=memory__pb2.AgentStateRequest.SerializeToString,
                response_deserializer=memory__pb2.AgentState.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/aios.memory.MemoryService/SemanticSearch',
                request_serializer=memory__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=memory__pb2.SearchResults.FromString,
                _registered_method=True)
        self.StoreProcedure = channel.unary_unary(
                '/aios.memory.MemoryService/StoreProcedure',
                request_serializer=memory__pb2.Procedure.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.StoreIncident = channel.unary_unary(
                '/aios.memory.MemoryService/StoreIncident',
                request_serializer=memory__pb2.Incident.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.StoreConfigChange = channel.unary_unary(
                '/aios.memory.MemoryService/StoreConfigChange',
                request_serializer=memory__pb2.ConfigChange.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/aios.memory.MemoryService/SearchKnowledge',
                request_serializer=memory__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=memory__pb2.SearchResults.FromString,
                _registered_method=True)
        self.AddKnowledge = channel.unary_unary(
                '/aios.memory.MemoryService/AddKnowledge',
                request_serializer=memory__pb2.KnowledgeEntry.SerializeToString,
                response_deserializer=memory__pb2.Empty.FromString,
                _registered_method=True)
        self.AssembleContext = channel.unary_unary(
                '/aios.memory.MemoryService/AssembleContext',
                request_serializer=memory__pb2.ContextRequest.SerializeToString,
                response_deserializer=memory__pb2.ContextResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushEvent(self, request, context):
        """Operational Memory (hot, in-memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreGoal(self, request, context):
        """Working Memory (warm, SQLite)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveGoals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasksForGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreToolCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorePattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatternStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreAgentState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Long-Term Memory (cold, SQLite + vectors)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreProcedure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreConfigChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """Knowledge Base
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssembleContext(self, request, context):
        """Context Assembly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PushEvent,
                    request_deserializer=memory__pb2.Event.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'GetRecentEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentEvents,
                    request_deserializer=memory__pb2.RecentEventsRequest.FromString,
                    response_serializer=memory__pb2.EventList.SerializeToString,
            ),
            'UpdateMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetric,
                    request_deserializer=memory__pb2.MetricUpdate.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'GetMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetric,
                    request_deserializer=memory__pb2.MetricRequest.FromString,
                    response_serializer=memory__pb2.MetricValue.SerializeToString,
            ),
            'GetSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemSnapshot,
                    request_deserializer=memory__pb2.Empty.FromString,
                    response_serializer=memory__pb2.SystemSnapshot.SerializeToString,
            ),
            'StoreGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreGoal,
                    request_deserializer=memory__pb2.GoalRecord.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'UpdateGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGoal,
                    request_deserializer=memory__pb2.GoalUpdate.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'GetActiveGoals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveGoals,
                    request_deserializer=memory__pb2.Empty.FromString,
                    response_serializer=memory__pb2.GoalList.SerializeToString,
            ),
            'StoreTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTask,
                    request_deserializer=memory__pb2.TaskRecord.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'GetTasksForGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasksForGoal,
                    request_deserializer=memory__pb2.GoalIdRequest.FromString,
                    response_serializer=memory__pb2.TaskList.SerializeToString,
            ),
            'StoreToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreToolCall,
                    request_deserializer=memory__pb2.ToolCallRecord.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'StoreDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDecision,
                    request_deserializer=memory__pb2.Decision.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'StorePattern': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePattern,
                    request_deserializer=memory__pb2.Pattern.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'FindPattern': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPattern,
                    request_deserializer=memory__pb2.PatternQuery.FromString,
                    response_serializer=memory__pb2.PatternResult.SerializeToString,
            ),
            'UpdatePatternStats': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatternStats,
                    request_deserializer=memory__pb2.PatternStatsUpdate.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'StoreAgentState': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreAgentState,
                    request_deserializer=memory__pb2.AgentState.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'GetAgentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentState,
                    request_deserializer=memory__pb2.AgentStateRequest.FromString,
                    response_serializer=memory__pb2.AgentState.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=memory__pb2.SemanticSearchRequest.FromString,
                    response_serializer=memory__pb2.SearchResults.SerializeToString,
            ),
            'StoreProcedure': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreProcedure,
                    request_deserializer=memory__pb2.Procedure.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'StoreIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreIncident,
                    request_deserializer=memory__pb2.Incident.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'StoreConfigChange': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreConfigChange,
                    request_deserializer=memory__pb2.ConfigChange.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=memory__pb2.SemanticSearchRequest.FromString,
                    response_serializer=memory__pb2.SearchResults.SerializeToString,
            ),
            'AddKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddKnowledge,
                    request_deserializer=memory__pb2.KnowledgeEntry.FromString,
                    response_serializer=memory__pb2.Empty.SerializeToString,
            ),
            'AssembleContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AssembleContext,
                    request_deserializer=memory__pb2.ContextRequest.FromString,
                    response_serializer=memory__pb2.ContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.memory.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.memory.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/PushEvent',
            memory__pb2.Event.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetRecentEvents',
            memory__pb2.RecentEventsRequest.SerializeToString,
            memory__pb2.EventList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/UpdateMetric',
            memory__pb2.MetricUpdate.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetMetric',
            memory__pb2.MetricRequest.SerializeToString,
            memory__pb2.MetricValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetSystemSnapshot',
            memory__pb2.Empty.SerializeToString,
            memory__pb2.SystemSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreGoal',
            memory__pb2.GoalRecord.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/UpdateGoal',
            memory__pb2.GoalUpdate.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveGoals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetActiveGoals',
            memory__pb2.Empty.SerializeToString,
            memory__pb2.GoalList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreTask',
            memory__pb2.TaskRecord.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTasksForGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetTasksForGoal',
            memory__pb2.GoalIdRequest.SerializeToString,
            memory__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreToolCall',
            memory__pb2.ToolCallRecord.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreDecision',
            memory__pb2.Decision.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorePattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StorePattern',
            memory__pb2.Pattern.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/FindPattern',
            memory__pb2.PatternQuery.SerializeToString,
            memory__pb2.PatternResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePatternStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/UpdatePatternStats',
            memory__pb2.PatternStatsUpdate.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreAgentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreAgentState',
            memory__pb2.AgentState.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/GetAgentState',
            memory__pb2.AgentStateRequest.SerializeToString,
            memory__pb2.AgentState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/SemanticSearch',
            memory__pb2.SemanticSearchRequest.SerializeToString,
            memory__pb2.SearchResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreProcedure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreProcedure',
            memory__pb2.Procedure.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreIncident',
            memory__pb2.Incident.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreConfigChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/StoreConfigChange',
            memory__pb2.ConfigChange.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/SearchKnowledge',
            memory__pb2.SemanticSearchRequest.SerializeToString,
            memory__pb2.SearchResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/AddKnowledge',
            memory__pb2.KnowledgeEntry.SerializeToString,
            memory__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssembleContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.memory.MemoryService/AssembleContext',
            memory__pb2.ContextRequest.SerializeToString,
            memory__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
