# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGoal = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/SubmitGoal',
                request_serializer=orchestrator__pb2.SubmitGoalRequest.SerializeToString,
                response_deserializer=common__pb2.GoalId.FromString,
                _registered_method=True)
        self.GetGoalStatus = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/GetGoalStatus',
                request_serializer=common__pb2.GoalId.SerializeToString,
                response_deserializer=orchestrator__pb2.GoalStatusResponse.FromString,
                _registered_method=True)
        self.CancelGoal = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/CancelGoal',
                request_serializer=common__pb2.GoalId.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.ListGoals = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/ListGoals',
                request_serializer=orchestrator__pb2.ListGoalsRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.GoalListResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/RegisterAgent',
                request_serializer=common__pb2.AgentRegistration.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.UnregisterAgent = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/UnregisterAgent',
                request_serializer=common__pb2.AgentId.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/Heartbeat',
                request_serializer=orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/ListAgents',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=orchestrator__pb2.AgentListResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/GetSystemStatus',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=orchestrator__pb2.SystemStatusResponse.FromString,
                _registered_method=True)
        self.GetAssignedTask = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/GetAssignedTask',
                request_serializer=common__pb2.AgentId.SerializeToString,
                response_deserializer=common__pb2.Task.FromString,
                _registered_method=True)
        self.ReportTaskResult = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/ReportTaskResult',
                request_serializer=common__pb2.TaskResult.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RequestCapability = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/RequestCapability',
                request_serializer=orchestrator__pb2.CapabilityRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.CapabilityResponse.FromString,
                _registered_method=True)
        self.RevokeCapability = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/RevokeCapability',
                request_serializer=orchestrator__pb2.CapabilityRevocation.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/CreateSchedule',
                request_serializer=orchestrator__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/ListSchedules',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=orchestrator__pb2.ScheduleListResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/DeleteSchedule',
                request_serializer=orchestrator__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/RegisterNode',
                request_serializer=orchestrator__pb2.NodeRegistration.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.NodeHeartbeat = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/NodeHeartbeat',
                request_serializer=orchestrator__pb2.NodeStatus.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/aios.orchestrator.Orchestrator/ListNodes',
                request_serializer=orchestrator__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.NodeListResponse.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitGoal(self, request, context):
        """Goal management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoalStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGoals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Agent registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """System status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignedTask(self, request, context):
        """Agent task dispatch (polling model)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCapability(self, request, context):
        """Capability management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Scheduled goals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Multi-node cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGoal,
                    request_deserializer=orchestrator__pb2.SubmitGoalRequest.FromString,
                    response_serializer=common__pb2.GoalId.SerializeToString,
            ),
            'GetGoalStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoalStatus,
                    request_deserializer=common__pb2.GoalId.FromString,
                    response_serializer=orchestrator__pb2.GoalStatusResponse.SerializeToString,
            ),
            'CancelGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoal,
                    request_deserializer=common__pb2.GoalId.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'ListGoals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGoals,
                    request_deserializer=orchestrator__pb2.ListGoalsRequest.FromString,
                    response_serializer=orchestrator__pb2.GoalListResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=common__pb2.AgentRegistration.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'UnregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAgent,
                    request_deserializer=common__pb2.AgentId.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=orchestrator__pb2.AgentListResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=orchestrator__pb2.SystemStatusResponse.SerializeToString,
            ),
            'GetAssignedTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignedTask,
                    request_deserializer=common__pb2.AgentId.FromString,
                    response_serializer=common__pb2.Task.SerializeToString,
            ),
            'ReportTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskResult,
                    request_deserializer=common__pb2.TaskResult.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RequestCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCapability,
                    request_deserializer=orchestrator__pb2.CapabilityRequest.FromString,
                    response_serializer=orchestrator__pb2.CapabilityResponse.SerializeToString,
            ),
            'RevokeCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCapability,
                    request_deserializer=orchestrator__pb2.CapabilityRevocation.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=orchestrator__pb2.CreateScheduleRequest.FromString,
                    response_serializer=orchestrator__pb2.ScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=orchestrator__pb2.ScheduleListResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=orchestrator__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=orchestrator__pb2.NodeRegistration.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'NodeHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeHeartbeat,
                    request_deserializer=orchestrator__pb2.NodeStatus.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=orchestrator__pb2.ListNodesRequest.FromString,
                    response_serializer=orchestrator__pb2.NodeListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.orchestrator.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.orchestrator.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/SubmitGoal',
            orchestrator__pb2.SubmitGoalRequest.SerializeToString,
            common__pb2.GoalId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGoalStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/GetGoalStatus',
            common__pb2.GoalId.SerializeToString,
            orchestrator__pb2.GoalStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/CancelGoal',
            common__pb2.GoalId.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGoals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/ListGoals',
            orchestrator__pb2.ListGoalsRequest.SerializeToString,
            orchestrator__pb2.GoalListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/RegisterAgent',
            common__pb2.AgentRegistration.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/UnregisterAgent',
            common__pb2.AgentId.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/Heartbeat',
            orchestrator__pb2.HeartbeatRequest.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/ListAgents',
            common__pb2.Empty.SerializeToString,
            orchestrator__pb2.AgentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/GetSystemStatus',
            common__pb2.Empty.SerializeToString,
            orchestrator__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignedTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/GetAssignedTask',
            common__pb2.AgentId.SerializeToString,
            common__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/ReportTaskResult',
            common__pb2.TaskResult.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/RequestCapability',
            orchestrator__pb2.CapabilityRequest.SerializeToString,
            orchestrator__pb2.CapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/RevokeCapability',
            orchestrator__pb2.CapabilityRevocation.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/CreateSchedule',
            orchestrator__pb2.CreateScheduleRequest.SerializeToString,
            orchestrator__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/ListSchedules',
            common__pb2.Empty.SerializeToString,
            orchestrator__pb2.ScheduleListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/DeleteSchedule',
            orchestrator__pb2.DeleteScheduleRequest.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/RegisterNode',
            orchestrator__pb2.NodeRegistration.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/NodeHeartbeat',
            orchestrator__pb2.NodeStatus.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.orchestrator.Orchestrator/ListNodes',
            orchestrator__pb2.ListNodesRequest.SerializeToString,
            orchestrator__pb2.NodeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
