# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import runtime_pb2 as runtime__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/aios.runtime.AIRuntime/LoadModel',
                request_serializer=runtime__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=runtime__pb2.ModelStatus.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/aios.runtime.AIRuntime/UnloadModel',
                request_serializer=runtime__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/aios.runtime.AIRuntime/ListModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=runtime__pb2.ModelList.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/aios.runtime.AIRuntime/Infer',
                request_serializer=runtime__pb2.InferRequest.SerializeToString,
                response_deserializer=runtime__pb2.InferResponse.FromString,
                _registered_method=True)
        self.StreamInfer = channel.unary_stream(
                '/aios.runtime.AIRuntime/StreamInfer',
                request_serializer=runtime__pb2.InferRequest.SerializeToString,
                response_deserializer=runtime__pb2.InferChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aios.runtime.AIRuntime/HealthCheck',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.HealthStatus.FromString,
                _registered_method=True)


class AIRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=runtime__pb2.LoadModelRequest.FromString,
                    response_serializer=runtime__pb2.ModelStatus.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=runtime__pb2.UnloadModelRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=runtime__pb2.ModelList.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=runtime__pb2.InferRequest.FromString,
                    response_serializer=runtime__pb2.InferResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=runtime__pb2.InferRequest.FromString,
                    response_serializer=runtime__pb2.InferChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.runtime.AIRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.runtime.AIRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.runtime.AIRuntime/LoadModel',
            runtime__pb2.LoadModelRequest.SerializeToString,
            runtime__pb2.ModelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.runtime.AIRuntime/UnloadModel',
            runtime__pb2.UnloadModelRequest.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.runtime.AIRuntime/ListModels',
            common__pb2.Empty.SerializeToString,
            runtime__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.runtime.AIRuntime/Infer',
            runtime__pb2.InferRequest.SerializeToString,
            runtime__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aios.runtime.AIRuntime/StreamInfer',
            runtime__pb2.InferRequest.SerializeToString,
            runtime__pb2.InferChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.runtime.AIRuntime/HealthCheck',
            common__pb2.Empty.SerializeToString,
            common__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
