# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rruntime.proto\x12\x0c\x61ios.runtime\x1a\x0c\x63ommon.proto\"\x85\x01\n\x10LoadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontext_length\x18\x03 \x01(\x05\x12\x12\n\ngpu_layers\x18\x04 \x01(\x05\x12\x0f\n\x07threads\x18\x05 \x01(\x05\x12\x0c\n\x04port\x18\x06 \x01(\x05\"(\n\x12UnloadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"|\n\x0bModelStatus\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x11\n\tloaded_at\x18\x04 \x01(\x03\x12\x11\n\tlast_used\x18\x05 \x01(\x03\x12\x15\n\rrequest_count\x18\x06 \x01(\x03\"6\n\tModelList\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.aios.runtime.ModelStatus\"\xb4\x01\n\x0cInferRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x1a\n\x12intelligence_level\x18\x06 \x01(\t\x12\x18\n\x10requesting_agent\x18\x07 \x01(\t\x12\x0f\n\x07task_id\x18\x08 \x01(\t\"Z\n\rInferResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\x12\x12\n\nmodel_used\x18\x04 \x01(\t\"(\n\nInferChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32\x9b\x03\n\tAIRuntime\x12\x46\n\tLoadModel\x12\x1e.aios.runtime.LoadModelRequest\x1a\x19.aios.runtime.ModelStatus\x12\x44\n\x0bUnloadModel\x12 .aios.runtime.UnloadModelRequest\x1a\x13.aios.common.Status\x12\x39\n\nListModels\x12\x12.aios.common.Empty\x1a\x17.aios.runtime.ModelList\x12@\n\x05Infer\x12\x1a.aios.runtime.InferRequest\x1a\x1b.aios.runtime.InferResponse\x12\x45\n\x0bStreamInfer\x12\x1a.aios.runtime.InferRequest\x1a\x18.aios.runtime.InferChunk0\x01\x12<\n\x0bHealthCheck\x12\x12.aios.common.Empty\x1a\x19.aios.common.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMODELREQUEST']._serialized_start=46
  _globals['_LOADMODELREQUEST']._serialized_end=179
  _globals['_UNLOADMODELREQUEST']._serialized_start=181
  _globals['_UNLOADMODELREQUEST']._serialized_end=221
  _globals['_MODELSTATUS']._serialized_start=223
  _globals['_MODELSTATUS']._serialized_end=347
  _globals['_MODELLIST']._serialized_start=349
  _globals['_MODELLIST']._serialized_end=403
  _globals['_INFERREQUEST']._serialized_start=406
  _globals['_INFERREQUEST']._serialized_end=586
  _globals['_INFERRESPONSE']._serialized_start=588
  _globals['_INFERRESPONSE']._serialized_end=678
  _globals['_INFERCHUNK']._serialized_start=680
  _globals['_INFERCHUNK']._serialized_end=720
  _globals['_AIRUNTIME']._serialized_start=723
  _globals['_AIRUNTIME']._serialized_end=1134
# @@protoc_insertion_point(module_scope)
