# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/aios.tools.ToolRegistry/ListTools',
                request_serializer=tools__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=tools__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.GetTool = channel.unary_unary(
                '/aios.tools.ToolRegistry/GetTool',
                request_serializer=tools__pb2.GetToolRequest.SerializeToString,
                response_deserializer=tools__pb2.ToolDefinition.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/aios.tools.ToolRegistry/Execute',
                request_serializer=tools__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=tools__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/aios.tools.ToolRegistry/Rollback',
                request_serializer=tools__pb2.RollbackRequest.SerializeToString,
                response_deserializer=tools__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/aios.tools.ToolRegistry/Register',
                request_serializer=tools__pb2.RegisterToolRequest.SerializeToString,
                response_deserializer=tools__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/aios.tools.ToolRegistry/Deregister',
                request_serializer=tools__pb2.DeregisterToolRequest.SerializeToString,
                response_deserializer=tools__pb2.Status.FromString,
                _registered_method=True)


class ToolRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTools(self, request, context):
        """Discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Extension
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=tools__pb2.ListToolsRequest.FromString,
                    response_serializer=tools__pb2.ListToolsResponse.SerializeToString,
            ),
            'GetTool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTool,
                    request_deserializer=tools__pb2.GetToolRequest.FromString,
                    response_serializer=tools__pb2.ToolDefinition.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tools__pb2.ExecuteRequest.FromString,
                    response_serializer=tools__pb2.ExecuteResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=tools__pb2.RollbackRequest.FromString,
                    response_serializer=tools__pb2.RollbackResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=tools__pb2.RegisterToolRequest.FromString,
                    response_serializer=tools__pb2.RegisterToolResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=tools__pb2.DeregisterToolRequest.FromString,
                    response_serializer=tools__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.tools.ToolRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.tools.ToolRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/ListTools',
            tools__pb2.ListToolsRequest.SerializeToString,
            tools__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/GetTool',
            tools__pb2.GetToolRequest.SerializeToString,
            tools__pb2.ToolDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/Execute',
            tools__pb2.ExecuteRequest.SerializeToString,
            tools__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/Rollback',
            tools__pb2.RollbackRequest.SerializeToString,
            tools__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/Register',
            tools__pb2.RegisterToolRequest.SerializeToString,
            tools__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.tools.ToolRegistry/Deregister',
            tools__pb2.DeregisterToolRequest.SerializeToString,
            tools__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
